### ISSUE TITLE
probes should use named ports rather than port numbers

### ISSUE THREAD

**Issue by jcpunk** [intel/pcm#947]
The pcm container examples in https://github.com/intel/pcm/blob/master/pcm-kubernetes.yaml.experimental use port numbers for Libeness and Readiness rather than named ports.  The current Kubernetes best practices recommend using named ports instead of numbered ports for this purpose.

**Comment by rdementi** [comment]
@ppalucki FYI

**Comment by Shubham-Padkonde** [comment]
This looks already done on `master`. `pcm-kubernetes.yaml.experimental` names the container port and both probes reference it by name:

```yaml
        livenessProbe:
          httpGet:
            path: /
            port: pcm-metrics
        ports:
        - containerPort: 9738
          hostPort: 9738
          name: pcm-metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: pcm-metrics
```

The `Service` and `ServiceMonitor` further down the same file also target `pcm-metrics` by name, so there are no numeric probe ports left in it. Unless something else in the repository still uses numbers, this can probably be closed.
